name: Run PR Tests
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Cache Gradle dependencies
        uses: actions/cache@v6
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'oracle-openjdk'
          java-version: '21'

      - name: Modify gradlew permissions
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew shadowJar
